#pragma once


#define TRACER_TRACE_KERNEL
#define TRACER_NOVA_SUPPORT 1
#define TRACER_VINTER 1
#define TRACER_LOG_PATH "/home/simon/projects/mpktracer/build-vinter"

/* #undef TRACER_USE_PTRACE */

/* #undef TRACER_USE_PROTECT_INSTALL_MODE_KERNEL */
#define TRACER_USE_PROTECT_INSTALL_MODE_PTRACE

#define TRACER_USE_TRAMPOLINE_INSTALL_MODE_INLINE
/* #undef TRACER_USE_TRAMPOLINE_INSTALL_MODE_EXTRA */


/* #undef TRACER_USE_PROTECT_TOGGLE_MODE_DOUBLE_MMAP */
#define TRACER_USE_PROTECT_TOGGLE_MODE_INLINE

/* #undef TRACER_USE_HANDLER_MODE_INLINE */
#define TRACER_USE_HANDLER_MODE_EXTRA
